org: peterjcole
app: slack-giffy
service: bolt-js-receiver
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${param:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${param:SLACK_BOT_TOKEN}
    GIPHY_API_KEY: ${param:GIPHY_API_KEY}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
